'use client'

import Link from 'next/link'
import { ArrowUpRight, CalendarDays, MessageCircle, Users } from 'lucide-react'
import type { Booking, Tour } from '../lib/types'
import { BottomNav, Header } from './AppShell'
import { useTranslation } from './LanguageContext'

export default function MyBookingScreen({ booking, tour }: { booking: Booking | null; tour: Tour | null }) { const { t, language } = useTranslation(); const hasBooking = booking !== null && tour !== null; return <main className="app"><Header /><div className="page-top container"><div className="eyebrow">{t('myJourney')}</div><h1 className="serif">{t('booking')}</h1><div className="booking-layout"><article className="booking-card">{hasBooking ? <><span className="status">{t('requestSubmitted')}</span><h2>{tour.localizedTitle?.[language] || tour.title}</h2><p className="muted" style={{ fontSize: 12, margin: 0 }}>{booking.reference}</p><div className="booking-meta"><div><span><CalendarDays size={12} /> {t('date')}</span><strong>{booking.date}</strong></div><div><span><Users size={12} /> {t('travelers')}</span><strong>{booking.travelers}</strong></div><div><span>{t('priceUsd')}</span><strong>${booking.total}</strong></div></div></> : <><span className="status">{t('booking')}</span><h2>{t('myJourney')}</h2><p className="muted">{t('noBooking')}</p></>}</article>{hasBooking && <div className="timeline"><div className="timeline-item"><strong>{t('requestSubmitted')}</strong><span>{t('date')} · {t('requestSubmitted')}</span></div><div className="timeline-item"><strong>{t('managerContact')}</strong><span>{t('within15')}</span></div><div className="timeline-item"><strong>{t('bookingConfirmation')}</strong><span>{t('status')}: {t('requestSubmitted')}</span></div><div className="timeline-item"><strong>{t('trip')}</strong><span>September 14, 2026</span></div></div>}</div><Link href="/contact" className="primary booking-contact"><MessageCircle size={16} />{t('chat')}<ArrowUpRight size={15} /></Link></div><BottomNav /></main> }
