'use client'

import Link from 'next/link'
import { ArrowUpRight, CalendarDays, ChevronRight, CircleDollarSign, Compass, MessageSquare, TrendingUp } from 'lucide-react'
import { inquiries } from '../../lib/mock-data/inquiries'
import { useTranslation } from '../LanguageContext'
import { AdminShell } from './AdminShell'
import { AdminPageHeader, PanelHeading } from './AdminPanel'

export default function AdminDashboard() { const { t } = useTranslation(); const kpis = [{ label: t('allInquiries'), value: '142', trend: '+12.5%', icon: MessageSquare }, { label: t('booking'), value: '18', trend: '+4.2%', icon: CalendarDays }, { label: t('priceUsd'), value: '$34,800', trend: '+18.6%', icon: CircleDollarSign }, { label: t('active'), value: '6', trend: '+1', icon: Compass }]; return <AdminShell><AdminPageHeader overline="Monday, August 24, 2026" title={t('dashboard')} description={t('manageTours')} action={<Link className="admin-header-action" href="/dashboard/tours/builder">{t('openBuilder')} <ArrowUpRight size={16} /></Link>} /><div className="kpi-grid">{kpis.map(({ label, value, trend, icon: Icon }) => <article className="kpi-card" key={label}><div className="kpi-icon"><Icon size={18} /></div><span>{label}</span><strong className="serif">{value}</strong><small><TrendingUp size={12} /> {trend}</small></article>)}</div><section className="admin-panel inquiries-panel"><PanelHeading overline={t('latestActivity')} title={t('recentInquiries')} action={<Link href="/dashboard/inquiries">{t('viewAll')} <ChevronRight size={15} /></Link>} /><InquiryTable /></section><section className="admin-lower-grid"><article className="admin-panel next-panel"><div className="admin-overline">{t('atAGlance')}</div><h2>{t('monthlyFocus')}</h2><div className="progress-row"><div><span>{t('inquiryConversion')}</span><strong>62%</strong></div><div className="progress"><i style={{ width: '62%' }} /></div></div><div className="progress-row"><div><span>{t('response15')}</span><strong>84%</strong></div><div className="progress"><i style={{ width: '84%' }} /></div></div><Link href="/dashboard/analytics" className="panel-link">{t('viewAnalytics')} <ArrowUpRight size={14} /></Link></article><article className="admin-panel next-panel sand-panel"><div className="admin-overline">{t('quickAction')}</div><h2>{t('updateItinerary')}</h2><p>{t('editAll')}</p><Link href="/dashboard/tours/builder" className="admin-button">{t('openBuilder')} <ArrowUpRight size={15} /></Link></article></section></AdminShell> }

export function InquiryTable() { const { t } = useTranslation(); return <div className="inquiry-table"><div className="inquiry-row inquiry-head"><span>{t('customer')}</span><span>{t('tour')}</span><span>Kakao ID</span><span>{t('date')}</span><span>{t('status')}</span></div>{inquiries.map((inquiry) => <div className="inquiry-row" key={inquiry.id}><div className="customer-cell"><div className="customer-avatar">{inquiry.customer.split(' ').map((part) => part[0]).join('')}</div><strong>{inquiry.customer}</strong></div><span data-label={t('tour')}>{inquiry.tour}</span><span data-label="Kakao ID" className="muted-cell">{inquiry.kakao}</span><span data-label={t('date')} className="muted-cell">{inquiry.date}</span><span data-label={t('status')} className={`inquiry-status ${inquiry.status === 'Шинэ' ? 'new' : inquiry.status === 'Баталгаажсан' ? 'confirmed' : 'contacted'}`}>{inquiry.status}</span></div>)}</div> }
