'use client'

import Link from 'next/link'
import { ArrowUpRight, CalendarDays, ChevronRight, CircleDollarSign, Compass, MessageSquare, TrendingUp } from 'lucide-react'
import type { DashboardMetrics, Inquiry } from '../../lib/types'
import { useTranslation } from '../LanguageContext'
import { AdminShell } from './AdminShell'

export default function AdminDashboard({ metrics, inquiries }: { metrics: DashboardMetrics; inquiries: Inquiry[] }) { const { t } = useTranslation(); const kpis = [{ label: t('allInquiries'), value: String(metrics.totalBookings), trend: metrics.bookingTrend, icon: MessageSquare }, { label: t('booking'), value: String(metrics.monthlyBookings), trend: metrics.bookingTrend, icon: CalendarDays }, { label: t('priceUsd'), value: `$${metrics.revenue.toLocaleString()}`, trend: metrics.revenueTrend, icon: CircleDollarSign }, { label: t('active'), value: String(metrics.activeTours), trend: metrics.tourTrend, icon: Compass }]; return <AdminShell><header className="admin-header"><div><div className="admin-overline">Monday, August 24, 2026</div><h1>{t('dashboard')}</h1><p>{t('manageTours')}</p></div><Link className="admin-header-action" href="/dashboard/tours/builder">{t('openBuilder')} <ArrowUpRight size={16} /></Link></header><div className="kpi-grid">{kpis.map(({ label, value, trend, icon: Icon }) => <article className="kpi-card" key={label}><div className="kpi-icon"><Icon size={18} /></div><span>{label}</span><strong className="serif">{value}</strong><small><TrendingUp size={12} /> {trend}</small></article>)}</div><section className="admin-panel inquiries-panel"><div className="panel-heading"><div><div className="admin-overline">{t('latestActivity')}</div><h2>{t('recentInquiries')}</h2></div><Link href="/dashboard/inquiries">{t('viewAll')} <ChevronRight size={15} /></Link></div><InquiryTable inquiries={inquiries} /></section><section className="admin-lower-grid"><article className="admin-panel next-panel"><div className="admin-overline">{t('atAGlance')}</div><h2>{t('monthlyFocus')}</h2><div className="progress-row"><div><span>{t('inquiryConversion')}</span><strong>62%</strong></div><div className="progress"><i style={{ width: '62%' }} /></div></div><div className="progress-row"><div><span>{t('response15')}</span><strong>84%</strong></div><div className="progress"><i style={{ width: '84%' }} /></div></div><Link href="/dashboard/analytics" className="panel-link">{t('viewAnalytics')} <ArrowUpRight size={14} /></Link></article><article className="admin-panel next-panel sand-panel"><div className="admin-overline">{t('quickAction')}</div><h2>{t('updateItinerary')}</h2><p>{t('editAll')}</p><Link href="/dashboard/tours/builder" className="admin-button">{t('openBuilder')} <ArrowUpRight size={15} /></Link></article></section></AdminShell> }

export function InquiryTable({ inquiries }: { inquiries: Inquiry[] }) { const { t } = useTranslation(); return <div className="inquiry-table"><div className="inquiry-row inquiry-head"><span>{t('customer')}</span><span>{t('tour')}</span><span>Kakao ID</span><span>{t('date')}</span><span>{t('status')}</span></div>{inquiries.map((inquiry) => <div className="inquiry-row" key={inquiry.id}><div className="customer-cell"><div className="customer-avatar">{inquiry.customer.split(' ').map((part) => part[0]).join('')}</div><strong>{inquiry.customer}</strong></div><span data-label={t('tour')}>{inquiry.tour}</span><span data-label="Kakao ID" className="muted-cell">{inquiry.kakao}</span><span data-label={t('date')} className="muted-cell">{inquiry.date}</span><span data-label={t('status')} className={`inquiry-status ${inquiry.status === 'Шинэ' ? 'new' : inquiry.status === 'Баталгаажсан' ? 'confirmed' : 'contacted'}`}>{inquiry.status}</span></div>)}</div> }
