'use client'

import Image from 'next/image'
import { GripVertical, ImagePlus, Plus, Save, Trash2, Upload, X } from 'lucide-react'
import { ChangeEvent, Dispatch, useReducer, useState } from 'react'
import { featuredTour } from '../../lib/mock-data/tours'
import { ItineraryDay, Language, Tour } from '../../lib/types'
import TourDetailScreen from '../TourDetailScreen'
import { useTranslation } from '../LanguageContext'
import { AdminShell } from './AdminShell'

type Action = { type: 'tour'; field: keyof Tour; value: string | number } | { type: 'day'; index: number; field: keyof ItineraryDay; value: string | string[] } | { type: 'description'; index: number; language: Language; value: string } | { type: 'meal'; index: number; meal: string } | { type: 'add' } | { type: 'remove'; index: number } | { type: 'image'; index: number; value: string }
const initialTour: Tour = { ...featuredTour, title: 'Говийн гайхамшигт аялал', localizedTitle: { mn: 'Говийн гайхамшигт аялал', kr: '고비 익스프레스 & 낙타 트레킹', en: featuredTour.title }, itinerary: featuredTour.itinerary.map((day) => ({ ...day, descriptions: { mn: 'Өглөө Улаанбаатар хотоос хөдөлж Монголын үзэсгэлэнт байгальтай танилцана.', kr: '울란바토르에서 출발해 몽골ын 아름다운 풍경을 만납니다.', en: 'Depart Ulaanbaatar and discover Mongolia’s open landscapes.' } })) }
function reducer(tour: Tour, action: Action): Tour { if (action.type === 'tour') return { ...tour, [action.field]: action.value }; if (action.type === 'day') return { ...tour, itinerary: tour.itinerary.map((day, index) => index === action.index ? { ...day, [action.field]: action.value } : day) }; if (action.type === 'description') return { ...tour, itinerary: tour.itinerary.map((day, index) => index === action.index ? { ...day, descriptions: { ...day.descriptions, [action.language]: action.value } } : day) }; if (action.type === 'meal') return { ...tour, itinerary: tour.itinerary.map((day, index) => index === action.index ? { ...day, meals: day.meals.includes(action.meal) ? day.meals.filter((meal) => meal !== action.meal) : [...day.meals, action.meal] } : day) }; if (action.type === 'add') { const day: ItineraryDay = { day: tour.itinerary.length + 1, title: 'Шинэ аяллын өдөр', distance: '—', meals: [], accommodation: 'Гэр бааз', activities: [], image: featuredTour.image, descriptions: { mn: '', kr: '', en: '' } }; return { ...tour, itinerary: [...tour.itinerary, day] } } if (action.type === 'remove') return { ...tour, itinerary: tour.itinerary.filter((_, index) => index !== action.index).map((day, index) => ({ ...day, day: index + 1 })) }; return { ...tour, itinerary: tour.itinerary.map((day, index) => index === action.index ? { ...day, image: action.value } : day) } }

export default function ItineraryBuilder() { const { t } = useTranslation(); const [tour, dispatch] = useReducer(reducer, initialTour); const [activeLanguage, setActiveLanguage] = useState<Language>('mn'); const [saved, setSaved] = useState(false); return <AdminShell><header className="admin-header builder-header"><div><div className="admin-overline">{t('journeyEditor')}</div><h1>{t('editJourney')}</h1></div><button className="admin-button" onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 1800) }}><Save size={16} />{saved ? t('saved') : t('save')}</button></header><div className="builder-layout"><section className="builder-form"><div className="admin-panel editor-panel"><div className="panel-heading"><div><div className="admin-overline">{t('collection')}</div><h2>{t('generalInfo')}</h2></div></div><label className="admin-label">{t('title')}<input value={tour.title} onChange={(event) => dispatch({ type: 'tour', field: 'title', value: event.target.value })} /></label><label className="admin-label">{t('description')}<textarea value={tour.subtitle} onChange={(event) => dispatch({ type: 'tour', field: 'subtitle', value: event.target.value })} /></label><div className="form-two"><label className="admin-label">{t('duration')}<input value={tour.duration} onChange={(event) => dispatch({ type: 'tour', field: 'duration', value: event.target.value })} /></label><label className="admin-label">{t('priceUsd')}<input type="number" value={tour.priceUsd} onChange={(event) => dispatch({ type: 'tour', field: 'priceUsd', value: Number(event.target.value) })} /></label></div></div><div className="builder-heading"><div><div className="admin-overline">{t('dayByDay')}</div><h2>{t('route')}</h2></div><button className="admin-quiet-button" onClick={() => dispatch({ type: 'add' })}><Plus size={15} />{t('addDay')}</button></div>{tour.itinerary.map((day, index) => <DayEditor key={`${day.day}-${index}`} day={day} index={index} activeLanguage={activeLanguage} setActiveLanguage={setActiveLanguage} dispatch={dispatch} onRemove={() => dispatch({ type: 'remove', index })} />)}</section><aside className="preview-column"><div className="preview-label"><span>{t('livePreview')}</span><span className="live-dot">● {t('live')}</span></div><div className="device-shell"><TourDetailScreen tourOverride={tour} /></div></aside></div></AdminShell> }

function DayEditor({ day, index, activeLanguage, setActiveLanguage, dispatch, onRemove }: { day: ItineraryDay; index: number; activeLanguage: Language; setActiveLanguage: (language: Language) => void; dispatch: Dispatch<Action>; onRemove: () => void }) { const { t, setLanguage } = useTranslation(); const meals = [{ key: 'Breakfast', label: t('breakfast') }, { key: 'Lunch', label: t('lunch') }, { key: 'Dinner', label: t('dinner') }]; const upload = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) dispatch({ type: 'image', index, value: URL.createObjectURL(file) }) }; return <article className="day-editor admin-panel"><div className="day-editor-head"><div className="drag-handle"><GripVertical size={16} /><span>DAY {String(day.day).padStart(2, '0')}</span></div><button className="delete-button" onClick={onRemove} aria-label={t('deleteDay')}><Trash2 size={16} /></button></div><label className="admin-label">{t('title')}<input value={day.title} onChange={(event) => dispatch({ type: 'day', index, field: 'title', value: event.target.value })} /></label><label className="admin-label">{t('routeLabel')}<input value={day.distance || ''} onChange={(event) => dispatch({ type: 'day', index, field: 'distance', value: event.target.value })} /></label><div className="form-two"><label className="admin-label">{t('accommodation')}<select value={day.accommodation} onChange={(event) => dispatch({ type: 'day', index, field: 'accommodation', value: event.target.value })}><option>Гэр бааз</option><option>Зочид буудал</option><option>Майхан</option><option>Айл</option></select></label><div><span className="admin-label-text">{t('meals')}</span><div className="meal-checks">{meals.map((meal) => <label key={meal.key}><input type="checkbox" checked={day.meals.includes(meal.key)} onChange={() => dispatch({ type: 'meal', index, meal: meal.key })} />{meal.label}</label>)}</div></div></div><div className="language-tabs">{(['mn', 'kr', 'en'] as Language[]).map((language) => <button key={language} className={activeLanguage === language ? 'active' : ''} onClick={() => { setActiveLanguage(language); setLanguage(language) }}>{language.toUpperCase()}</button>)}</div><label className="admin-label">{t('description')} {activeLanguage.toUpperCase()}<textarea value={day.descriptions?.[activeLanguage] || ''} onChange={(event) => dispatch({ type: 'description', index, language: activeLanguage, value: event.target.value })} /></label><div className="upload-area"><ImagePlus size={19} /><span>{t('uploadImage')}</span><small>{t('imageLimit')}</small><label className="upload-button"><Upload size={14} />{t('chooseImage')}<input type="file" accept="image/*" onChange={upload} /></label>{day.image && <div className="upload-preview"><Image src={day.image} alt={t('mainImage')} width={54} height={42} /><button onClick={() => dispatch({ type: 'image', index, value: '' })} aria-label={t('cancel')}><X size={13} /></button></div>}</div></article> }
